title: MyFlow: A successful git branching model for DevOps teams
description: >-
  MyFlow is a lightweight git workflow that allows you to use the full 
  power of git and still collaborate with your peers with pull requests.
twitter_username: mike_kaufmann
github_username: wulfland
theme: jekyll-theme-cayman
